tracker_type: botsort

track_high_thresh: 0.5
track_low_thresh: 0.1
new_track_thresh: 0.6
track_buffer: 50
match_thresh: 0.7
proximity_thresh: 0.6
appearance_thresh: 0.25
cmc_method: osnet_x1_0 
gmc_method: none
with_reid: True
model: auto
fuse_score: False